
name: Nix (nixpkgs)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install dependencies
        run: |
          cd nix/nixpkgs
          nix-shell --run "true"
        timeout-minutes: 2
      - name: Try to import cartopy
        run: |
          cd nix/nixpkgs
          nix-shell --run "python -c 'import cartopy'"
          nix-shell --run "python -c 'import tensorflow'"
          nix-shell --run "python -c 'import xgcm'"
